name: Test Secrets

on: [workflow_dispatch]

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Verify SECRET_1 is set correctly
        run: |
          if [[ -z "${{ secrets.LOGIN_PASSWORD_CORRECT }}" ]]; then
            echo "SECRET_1 is not set"
            exit 1
          else
            echo "SECRET_1 is set"
          fi

      - name: Verify SECRET_2 is set correctly
        run: |
          if [[ -z "${{ secrets.LOGIN_USERNAME_CORRECT }}" ]]; then
            echo "SECRET_1 is not set"
            exit 1
          else
            echo "SECRET_1 is set"
          fi
